### ISSUE TITLE
Terminal Compiles, Travis Doesn't. 

### ISSUE THREAD

**Issue by TestingYG** [cisc3130/4-map#2]
![screen shot 2017-12-04 at 2 21 52 pm](https://user-images.githubusercontent.com/31413025/33571622-98467554-d8fe-11e7-9759-c271c4493846.png)

**Comment by Brendafried** [comment]
#include algorithm 
that worked for me
@TestingYG

**Comment by TestingYG** [comment]
@Brendafried Thanks (:
