### ISSUE TITLE
error in running the code

### ISSUE THREAD

**Issue by fayrouz-mikhael** [cisc3130/4-map#3]
[Error] passing 'const string {aka const std::basic_string<char>}' as 'this' argument of 'std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::operator=(const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc> = std::basic_string<char>]' discards qualifiers [-fpermissive]

Thank you.

@rivlev

**Comment by rivlev** [comment]
See #1
