### ISSUE TITLE
error ( return 0 )

### ISSUE THREAD

**Issue by fayrouz-mikhael** [cisc3130/4-map#4]
cout << "Usage: ./calc_bigrams <FILENAME>\n";
--------------------------------------------------------
process exited with return value 0;

I don't know why it's giving me that when I run my code

thank you.
@rivlev

**Comment by TestingYG** [comment]
you have to run it in a terminal or push it to Travis. 

for terminal: 
1. g++ --std=c++11 main.cpp
2. ./a.out gutenberg/"filename"

filenames: 
whitman-leaves.txt 
shakespeare-macbeth.txt 
austen-emma.txt

**Comment by fayrouz-mikhael** [comment]
Thank you 
@TestingYG
